import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import LoginBtn from '../../components/login-btn'
import styles from '../../styles/Home.module.css'

export default function LoginTest() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next-Auth-Sqlite3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.center}>
        <LoginBtn />
      </header>
    
      <div>
        <p> Alternate page to test login persistance.</p>
        <br />
        <Link href="/"><a >Return to Index</a></Link>
      </div>

    </div>
  )
}
