import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import LoginBtn from '../components/login-btn'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next-Auth-Sqlite3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.center}>
        <LoginBtn />
      </header>

      <div className='center'>
        <Link href="/login-test"><a >Login-Test A</a></Link> <br />
        <br />
        <Link href="/login-test/b"><a >Login-Test B</a></Link> <br />
        <br />
        <Link href="/login-test/c"><a >Login-Test C</a></Link> <br />
      </div>
    </div>
  )
}
